# SwiftLint Configuration for TemporalKit
# Balances code quality with practical development needs

# Files to include/exclude
included:
  - Sources
  - Tests

excluded:
  - Sources/TemporalKitDemo
  - .build
  - Package.swift

# Enable optional rules
opt_in_rules:
  - force_unwrapping
  - multiline_parameters

# Rules to allow in test files or specific contexts
force_unwrapping:
  severity: warning

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 25
  error: 40

function_parameter_count:
  warning: 8
  error: 12

# Allow mathematical variable names in algorithms
identifier_name:
  min_length: 1
  validates_start_with_lowercase: warning
  allowed_symbols: ["_"]

# Allow longer generic type names
generic_type_name:
  max_length: 30

# Allow longer lines for complex expressions
line_length:
  warning: 150
  error: 200

# Allow larger tuples for algorithm state
large_tuple:
  warning: 4
  error: 6

# Disable strict formatting rules for complex algorithms
multiline_parameters:
  severity: warning

vertical_parameter_alignment:
  severity: warning

# Allow for-if patterns in algorithms
for_where:
  severity: warning