name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SWIFT_VERSION: '5.10'

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        swift: ['5.10']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2.2.0
      with:
        swift-version: ${{ matrix.swift }}
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v


  lint:
    name: SwiftLint
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  build-docs:
    name: Build Documentation
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Build documentation
      run: |
        swift package --allow-writing-to-directory ./docs \
          generate-documentation --target TemporalKit \
          --output-path ./docs \
          --disable-indexing \
          --transform-for-static-hosting
    
    - name: Create documentation archive
      run: |
        tar -czf documentation.tar.gz ./docs
    
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: documentation.tar.gz

  performance-test:
    name: Performance Tests
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2.2.0
      with:
        swift-version: '5.10'
    
    - name: Run performance tests
      run: |
        swift test --filter TemporalKitTests.PerformanceTests